import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { COLORS, SPACING, RADIUS, BUTTON_STYLES, createGlowEffect } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundDark,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xl,
  },
  title: {
    fontSize: RFValue(24),
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: SPACING.xs,
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  subtitle: {
    fontSize: RFValue(10),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: SPACING.xl,
    fontStyle: 'italic',
  },
  decorativeContainer: {
    position: 'relative',
    height: hp(8),
    marginBottom: SPACING.xl,
  },
  bubble: {
    position: 'absolute',
    fontSize: RFValue(30),
    left: wp(20),
    top: SPACING.md,
  },
  bubble2: {
    left: wp(50),
    top: 0,
    fontSize: RFValue(25),
  },
  bubble3: {
    left: wp(70),
    top: SPACING.lg,
    fontSize: RFValue(35),
  },
  inputContainer: {
    marginBottom: SPACING.lg,
  },
  label: {
    fontSize: RFValue(10),
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
    fontWeight: '600',
  },
  inputWrapper: {
    position: 'relative',
  },
  input: {
    backgroundColor: COLORS.cardBackground,
    borderWidth: 2,
    borderColor: COLORS.cardBackgroundLight,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    fontSize: RFValue(10),
    color: COLORS.textPrimary,
    minHeight: hp(6),
    shadowColor: COLORS.primary,
  },
  inputGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderPrimary,
    opacity: 0.5,
    pointerEvents: 'none',
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: SPACING.md,
    marginBottom: SPACING.xl,
    gap: SPACING.md,
  },
  loginButton: {
    ...BUTTON_STYLES.primary,
    flex: 1,
    paddingVertical: SPACING.md + SPACING.sm,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  loginButtonDisabled: {
    backgroundColor: COLORS.cardBackgroundLight,
    borderColor: COLORS.borderLight,
  },
  googleButton: {
    backgroundColor: '#4285f4',
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md + SPACING.sm,
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#4285f4',
    borderWidth: 2,
    borderColor: '#4285f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleButtonText: {
    color: COLORS.textPrimary,
    fontSize: RFValue(12),
    fontWeight: 'bold',
    textAlign: 'center',
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingIcon: {
    fontSize: RFValue(12),
    marginRight: SPACING.sm,
    color: COLORS.textPrimary,
  },
  loginButtonText: {
    color: COLORS.textPrimary,
    fontSize: RFValue(12),
    fontWeight: 'bold',
    textAlign: 'center',
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonGlow: {
    position: 'absolute',
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.borderSecondary,
    opacity: 0,
  },
  buttonGlowActive: {
    opacity: 1,
  },
  disclaimer: {
    fontSize: RFValue(11),
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: RFValue(16),
    fontStyle: 'italic',
  },
});