import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { COLORS, SPACING, RADIUS, createSciFiGlow } from '../../constants/theme';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: SPACING.xl,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: hp(5),
  },
  logo: {
    width: wp(80),
    height: hp(15),
    marginBottom: SPACING.md,
  },
  title: {
    fontSize: RFValue(10),
    top: wp(3.5),
    // bottom: -hp(20),
    fontWeight: '900',
    color: COLORS.white,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 2,
    textShadowColor: '#00d2ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
    // marginBottom: SPACING.sm,
  },
  loginFrame: {
    width: wp(90),
    height: hp(50),
    top: wp(80),
    right: wp(1),
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.xl,
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
  },
  frameHeader: {
    fontSize: RFValue(18),
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: SPACING.xl,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  inputContainer: {
    marginBottom: SPACING.lg,
    // top: wp(20)
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 5, 20, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.3)',
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    height: hp(5),
    left: wp(10),
    width: wp(60),
    top: wp(6),
  },
  inputIcon: {
    marginRight: SPACING.sm,
  },
  input: {
    flex: 1,
    fontSize: RFValue(10),
    color: COLORS.white,
    paddingVertical: 0,
  },
  eyeIcon: {
    padding: SPACING.sm,
    zIndex: 99,
  },
  forgotPassword: {
    color: '#00d2ff',
    // backgroundColor: '#eee',
    textAlign: 'center',
    fontSize: RFValue(10),
    marginBottom: SPACING.lg,
    top: wp(5),
    fontWeight: '600',
    opacity: 0.9,
  },
  loginButton: {
    height: hp(5.5),
    width: wp(60),
    left: wp(10),
    top: wp(4),
    borderRadius: RADIUS.md,
    overflow: 'hidden',
    marginBottom: SPACING.md,
    borderWidth: 1.5,
    borderColor: '#ffcc00',
    ...createSciFiGlow(),
  },
  buttonGradient: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginButtonText: {
    color: COLORS.white,
    fontSize: RFValue(12),
    fontWeight: '900',
    // textTransform: 'uppercase',
    letterSpacing: 1,
    // textShadowColor: 'rgba(0, 0, 0, 0.5)',
    // textShadowOffset: { width: 1, height: 1 },
    // textShadowRadius: 3,
  },
  googleButton: {
    height: hp(5.5),
    width: wp(60),
    left: wp(10),
    top: wp(4),
    borderRadius: RADIUS.md,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#4a90e2',
    marginBottom: SPACING.xl,
    ...createSciFiGlow(),
  },
  googleButtonText: {
    color: COLORS.white,
    fontSize: RFValue(14),
    fontWeight: '700',
  },
  footerText: {
    fontSize: RFValue(10),
    color: 'rgba(255, 255, 255, 0.5)',
    textAlign: 'center',
    marginTop: SPACING.md,
  },
});
