import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { COLORS, SPACING, RADIUS, CARD_STYLES, createBackgroundOverlay } from '../../constants/theme';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  container: { 
    flex: 1, 
    ...createBackgroundOverlay(),
  },
  header: {
    paddingTop: hp(6),
    paddingBottom: SPACING.md,
    paddingHorizontal: SPACING.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: RFValue(18),
    left: wp(12),
    fontWeight: 'bold',
    color: COLORS.primary,
    flex: 1,
    textAlign: 'center',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    position: 'relative',
  },
  settingsButton: {
    padding: SPACING.xs,
  },
  settingsIcon: {
    width: wp(12),
    height: wp(12),
    left: wp(3)
  },
  menuButton: {
    padding: SPACING.sm,
    backgroundColor: COLORS.cardBackground,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    left: wp(2),
    borderColor: COLORS.borderLight,
  },
  dropdownMenu: {
    position: 'absolute',
    top: hp(6),
    right: 0,
    backgroundColor: COLORS.cardBackground,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    minWidth: wp(40),
    zIndex: 1000,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md - SPACING.xs,
    gap: SPACING.sm,
  },
  dropdownItemText: {
    fontSize: RFValue(12),
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginHorizontal: SPACING.sm,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: SPACING.lg,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: SPACING.md - SPACING.xs,
  },
  avatar: {
    width: wp(32),
    height: wp(32),
    borderRadius: RADIUS.lg,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  editBadge: {
    position: 'absolute',
    top: wp(26),
    left: wp(25),
    backgroundColor: COLORS.success,
    width: wp(10),
    height: wp(8),
    borderRadius: wp(5),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBackground,
  },
  editIcon: {
    fontSize: RFValue(14),
  },
  username: {
    fontSize: RFValue(18),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.xs,
    paddingVertical: SPACING.md,
    gap: SPACING.sm,
  },
  statCard: {
    flex: 1,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    alignItems: 'center',
    minHeight: hp(14),
    justifyContent: 'space-between',
    borderWidth: 2,
  },
  statCardGreen: {
    backgroundColor: COLORS.cardBackground,
    borderColor: COLORS.success,
  },
  statCardPurple: {
    backgroundColor: COLORS.cardBackground,
    borderColor: COLORS.info,
  },
  statCardBrown: {
    backgroundColor: COLORS.cardBackground,
    borderColor: COLORS.warning,
  },
  statIconContainer: {
    width: wp(12),
    height: wp(12),
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.cardBackgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.borderPrimary,
  },
  statNumber: {
    fontSize: RFValue(20),
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: hp(0.5),
  },
  statUnit: {
    fontSize: RFValue(16),
    fontWeight: 'normal',
  },
  statLabel: {
    fontSize: RFValue(6),
    fontWeight: '600',
    color: COLORS.textSecondary,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    marginHorizontal: SPACING.md + SPACING.sm,
    marginVertical: SPACING.xs,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.lg,
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
  },
  shareButtonText: {
    fontSize: RFValue(14),
    fontWeight: 'bold',
    color: COLORS.white,
  },
  menuContainer: {
    ...CARD_STYLES.base,
    marginHorizontal: SPACING.md,
    marginTop: SPACING.xs,
    marginBottom: SPACING.lg,
    paddingVertical: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.borderPrimary,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  menuIconContainer: {
    width: wp(12),
    height: wp(12),
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.cardBackgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIcon: {
    fontSize: RFValue(20),
  },
  menuItemText: {
    fontSize: RFValue(14),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  menuDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginHorizontal: SPACING.md,
  },
});
