import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  container: { 
    flex: 1, 
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  header: {
    paddingTop: hp(6),
    paddingBottom: hp(2),
    paddingHorizontal: wp(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: RFValue(18),
    left: wp(12),
    fontWeight: 'bold',
    color: COLORS.primary,
    flex: 1,
    textAlign: 'center',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
    position: 'relative',
  },
  settingsButton: {
    padding: wp(1),
  },
  settingsIcon: {
    width: wp(12),
    height: wp(12),
    left: wp(3)
  },
  menuButton: {
    padding: wp(2),
    backgroundColor: COLORS.gameOverlayLight,
    borderRadius: wp(6),
    borderWidth: 1,
    left: wp(2),
    borderColor: COLORS.borderLight,
  },
  dropdownMenu: {
    position: 'absolute',
    top: hp(6),
    right: 0,
    backgroundColor: COLORS.cardBackground,
    borderRadius: wp(3),
    borderWidth: 1,
    minWidth: wp(40),
    zIndex: 1000,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    gap: wp(3),
  },
  dropdownItemText: {
    fontSize: RFValue(12),
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginHorizontal: wp(2),
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: hp(3),
    // backgroundColor: COLORS.gameOverlayDark,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: hp(1.5),
  },
  avatar: {
    width: wp(32),
    height: wp(32),
    borderRadius: wp(8),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  editBadge: {
    position: 'absolute',
    top: wp(26),
    left: wp(25),
    backgroundColor: COLORS.success,
    width: wp(10),
    height: wp(8),
    borderRadius: wp(5),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBackground,
  },
  editIcon: {
    fontSize: RFValue(14),
  },
  username: {
    fontSize: RFValue(18),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    gap: wp(3),
  },
  statCard: {
    flex: 1,
    borderRadius: wp(4),
    padding: wp(4),
    alignItems: 'center',
    minHeight: hp(14),
    justifyContent: 'space-between',
    borderWidth: 2,
  },
  statCardGreen: {
    backgroundColor: COLORS.gameAccentLight,
    borderColor: COLORS.success,
  },
  statCardPurple: {
    backgroundColor: COLORS.gameAccentLight,
    borderColor: COLORS.info,
  },
  statCardBrown: {
    backgroundColor: COLORS.gameAccentLight,
    borderColor: COLORS.warning,
  },
  statIconContainer: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: COLORS.cardBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(1),
    borderWidth: 1,
    borderColor: COLORS.borderPrimary,
  },
  statNumber: {
    fontSize: RFValue(20),
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: hp(0.5),
  },
  statUnit: {
    fontSize: RFValue(16),
    fontWeight: 'normal',
  },
  statLabel: {
    fontSize: RFValue(6),
    fontWeight: '600',
    color: COLORS.textSecondary,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    marginHorizontal: wp(6),
    marginVertical: hp(1),
    paddingVertical: hp(2),
    borderRadius: wp(8),
    gap: wp(2),
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
  },
  shareButtonText: {
    fontSize: RFValue(14),
    fontWeight: 'bold',
    color: COLORS.white,
  },
  menuContainer: {
    backgroundColor: COLORS.cardBackground,
    marginHorizontal: wp(5),
    marginTop: hp(1),
    marginBottom: hp(3),
    borderRadius: wp(4),
    paddingVertical: hp(1),
    borderWidth: 1,
    borderColor: COLORS.borderPrimary,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
  },
  menuIconContainer: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: COLORS.gameAccentMedium,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: COLORS.borderPrimary,
  },
  menuIcon: {
    fontSize: RFValue(20),
  },
  menuItemText: {
    fontSize: RFValue(14),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  menuDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginHorizontal: wp(4),
  },
});
